export const reduxConstants = {
  SET_JS_VALUE: "SET_JS_VALUE",
  SET_CSS_VALUE: "SET_CSS_VALUE",
  SET_HTML_VALUE: "SET_HTML_VALUE",
  REFRESH_EDITORS_VALUE: "REFRESH_EDITORS_VALUE",
  CHANGE_EDITOR_LAYOUT: "CHANGE_EDITOR_LAYOUT",
};
